{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/dictionaryRepresentation()"},"abstract":[{"text":"해당 인스턴스의 프로퍼티 값들을 딕셔너리로 반환합니다. 값들의 키값은 프로퍼티 명과 동일하고, 값들의 타입은 모두 문자열입니다.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/dictionaryrepresentation()"]},{"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/dictionaryrepresentation()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"인스턴스 프로퍼티들의 딕셔너리 변환값","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"KakaoAd SDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct(im)dictionaryRepresentation","title":"dictionaryRepresentation()"},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct/dictionaryRepresentation()":{"kind":"symbol","type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/dictionaryrepresentation()","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/dictionaryRepresentation()","role":"symbol","title":"dictionaryRepresentation()","abstract":[{"text":"해당 인스턴스의 프로퍼티 값들을 딕셔너리로 반환합니다. 값들의 키값은 프로퍼티 명과 동일하고, 값들의 타입은 모두 문자열입니다.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","role":"collection","title":"KakaoAd SDK","abstract":[]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"type":"text","text":" "},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"title":"KakaoAdDetailProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdDetailProduct","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","type":"topic","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"dictionaryRepresentation","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dictionaryRepresentation"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"인스턴스 프로퍼티들의 딕셔너리 변환값","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"dictionaryRepresentation","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1dictionaryRepresentation()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"dictionaryRepresentation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1dictionaryRepresentation()\/fragments","op":"replace"},{"value":"KakaoAdDetailProduct","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title","op":"replace"},{"value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments","op":"replace"},{"value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}