{"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(name:quantity:price:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"]]},"sections":[],"abstract":[{"type":"text","text":"구매 이벤트를 전송할 때 Producs 파라메터의 세부 항목을 생성합니다. 구매 이벤트의 Products 파라메터는 Array고"},{"type":"text","text":" "},{"type":"text","text":"그 세부 항목의 타입은 KakaoAdDetailProduct 입니다."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"quantity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":", ","kind":"text"},{"text":"price","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"name","content":[{"inlineContent":[{"text":"상품명","type":"text"}],"type":"paragraph"}]},{"name":"quantity","content":[{"inlineContent":[{"type":"text","text":"상품수량"}],"type":"paragraph"}]},{"name":"price","content":[{"type":"paragraph","inlineContent":[{"text":"상품가격","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"KakaoAdDetailProduct instance","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/init(name:quantity:price:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/init(name:quantity:price:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithName:quantity:price:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct(im)initWithName:quantity:price:","role":"symbol","title":"init(name:quantity:price:)","modules":[{"name":"KakaoAd SDK"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"price","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct/init(name:quantity:price:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"구매 이벤트를 전송할 때 Producs 파라메터의 세부 항목을 생성합니다. 구매 이벤트의 Products 파라메터는 Array고"},{"type":"text","text":" "},{"type":"text","text":"그 세부 항목의 타입은 KakaoAdDetailProduct 입니다."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"price","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithName:quantity:price:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(name:quantity:price:)","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/init(name:quantity:price:)","title":"init(name:quantity:price:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"title":"KakaoAdDetailProduct","role":"symbol","abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"text":" ","type":"text"},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithName:quantity:price:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:quantity:price:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithName:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quantity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"quantity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"price:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"price","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"name","content":[{"inlineContent":[{"text":"상품명","type":"text"}],"type":"paragraph"}]},{"name":"quantity","content":[{"type":"paragraph","inlineContent":[{"text":"상품수량","type":"text"}]}]},{"name":"price","content":[{"inlineContent":[{"text":"상품가격","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"KakaoAdDetailProduct instance","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"initWithName:quantity:price:","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(name:quantity:price:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithName:quantity:price:"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(name:quantity:price:)\/fragments"},{"value":"KakaoAdDetailProduct","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title"},{"value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments"},{"value":[{"kind":"identifier","text":"KakaoAdDetailProduct"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}