{"variants":[{"paths":["\/documentation\/kakaoadsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","interfaceLanguage":"swift"},"primaryContentSections":[{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"iOS 앱에서 광고 성과 측정을 위한 주요 이벤트를 수집하고 전송하는 SDK입니다.","type":"text"}]}],"type":"aside","style":"note"},{"level":2,"anchor":"Overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"code":"KakaoAdSDK","type":"codeVoice"},{"text":"는 iOS 애플리케이션에서 앱 설치, 앱 실행, 회원가입, 장바구니 조회, 상품 조회, 검색, 구매 같은 이벤트를 수집하고 전송합니다.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"설치, 실행, 앱 내 구매 이벤트는 SDK가 자동으로 처리하며, 그 외 이벤트는 앱에서 명시적으로 호출해 연동합니다."}]}],"kind":"content"}],"metadata":{"externalID":"KakaoAdSDK","symbolKind":"module","modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Framework","title":"KakaoAd SDK","role":"collection"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"anchor":"시작하기","title":"시작하기"},{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"],"anchor":"핵심-타입","title":"핵심 타입"},{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"]},{"generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KCEvent"],"anchor":"Enumerations","title":"Enumerations"}],"sections":[],"kind":"symbol","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger":{"title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/logger","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/InstallSDK":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","role":"article","abstract":[],"title":"SDK 설치하기","type":"topic","url":"\/documentation\/kakaoadsdk\/installsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/GetTrackID":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","role":"article","abstract":[{"type":"text","text":"광고주 SDK를 사용하려면 먼저 광고 계정에 연결된 "},{"code":"Track ID","type":"codeVoice"},{"type":"text","text":"가 필요합니다."}],"title":"Track ID 발급받기","type":"topic","url":"\/documentation\/kakaoadsdk\/gettrackid"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KCEvent":{"title":"KCEvent","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk\/kcevent","navigatorTitle":[{"text":"KCEvent","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KCEvent","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KCEvent","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProjectSetting":{"abstract":[],"title":"프로젝트 설정","url":"\/documentation\/kakaoadsdk\/projectsetting","kind":"article","role":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"title":"KakaoAdDetailProduct","role":"symbol","abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"text":" ","type":"text"},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdSDKVersionNumber":{"url":"\/documentation\/kakaoadsdk\/kakaoadsdkversionnumber","fragments":[{"kind":"identifier","text":"KakaoAdSDKVersionNumber"}],"abstract":[],"title":"KakaoAdSDKVersionNumber","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdSDKVersionNumber"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/RequestIDFA":{"url":"\/documentation\/kakaoadsdk\/requestidfa","type":"topic","role":"article","title":"IDFA 추적 권한 요청","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","kind":"article","abstract":[{"type":"text","text":"광고 성과 측정을 정확하게 수행하려면 앱의 추적 권한 요청 시점과 SDK 활성화 시점을 함께 고려해야 합니다."}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"}],"navigatorTitle":[{"text":"LogChecker","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","url":"\/documentation\/kakaoadsdk\/logchecker","title":"LogChecker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdSDKVersionString":{"url":"\/documentation\/kakaoadsdk\/kakaoadsdkversionstring","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdSDKVersionString","title":"KakaoAdSDKVersionString","fragments":[{"text":"KakaoAdSDKVersionString","kind":"identifier"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"시작하기","anchor":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"]},{"title":"핵심 타입","anchor":"핵심-타입","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"]},{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"],"generated":true},{"generated":true,"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdSDKVersionNumber","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdSDKVersionString"]}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/title","value":"Logger","op":"replace"},{"value":[{"text":"Logger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/fragments"},{"value":[{"kind":"identifier","text":"Logger"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","value":"KakaoAdTracker"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","value":[{"kind":"identifier","text":"KakaoAdTracker"}]},{"value":[{"kind":"identifier","text":"KakaoAdTracker"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle"},{"op":"replace","value":"KakaoAdDetailProduct","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments","op":"replace","value":[{"kind":"identifier","text":"KakaoAdDetailProduct"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle","value":[{"kind":"identifier","text":"KakaoAdDetailProduct"}]},{"op":"replace","value":"LogChecker","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/title"},{"op":"replace","value":[{"text":"LogChecker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/fragments"},{"op":"replace","value":[{"text":"LogChecker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/navigatorTitle"}]}]}