{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/logchecker\/init"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@KakaoAdSDK@objc(cs)LogChecker(im)init","modules":[{"name":"KakaoAd SDK"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker"]]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"}],"navigatorTitle":[{"text":"LogChecker","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","url":"\/documentation\/kakaoadsdk\/logchecker","title":"LogChecker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker/init":{"url":"\/documentation\/kakaoadsdk\/logchecker\/init","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/init","abstract":[],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"LogChecker","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/title"},{"value":[{"text":"LogChecker","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/fragments"},{"value":[{"text":"LogChecker","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}