{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openLogConsole"},{"kind":"text","text":"()"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"metadata":{"symbolKind":"method","title":"openLogConsole()","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"openLogConsole","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"openLogConsole"},{"kind":"text","text":"()"}],"role":"symbol","externalID":"c:@M@KakaoAdSDK@objc(cs)LogChecker(cm)openLogConsole","modules":[{"name":"KakaoAd SDK"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/logchecker\/openlogconsole()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/logchecker\/openlogconsole()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/openLogConsole()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker"]]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker/openLogConsole()":{"kind":"symbol","url":"\/documentation\/kakaoadsdk\/logchecker\/openlogconsole()","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/openLogConsole()","role":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"openLogConsole"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"openLogConsole"},{"kind":"text","text":"()"}],"type":"topic","title":"openLogConsole()"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker":{"navigatorTitle":[{"text":"LogChecker","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogChecker"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/kakaoadsdk\/logchecker","title":"LogChecker","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"openLogConsole"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"openLogConsole"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"openLogConsole","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker~1openLogConsole()\/title","op":"replace","value":"openLogConsole"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker~1openLogConsole()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"openLogConsole"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/title","op":"replace","value":"LogChecker"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/fragments","op":"replace","value":[{"kind":"identifier","text":"LogChecker"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LogChecker"}]}]}]}