{"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"발급 경로","anchor":"%EB%B0%9C%EA%B8%89-%EA%B2%BD%EB%A1%9C"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"https:\/\/business.kakao.com","type":"reference"},{"type":"text","text":"에서 계정을 준비합니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"https:\/\/business.kakao.com\/pixel","isActive":true},{"text":" 페이지에서 ","type":"text"},{"code":"Track ID","type":"codeVoice"},{"type":"text","text":" 발급 절차를 진행합니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"발급이 완료되면 앱에서 "},{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"type":"text","text":"에 설정합니다."}]}]}]},{"type":"heading","anchor":"%EB%8B%A4%EC%9D%8C-%EB%8B%A8%EA%B3%84","text":"다음 단계","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"Track ID"},{"type":"text","text":" 발급이 끝나면 아래 문서를 순서대로 진행합니다."}]},{"items":[{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","type":"reference","isActive":true}]}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"}],"type":"paragraph"}]}],"type":"unorderedList"}],"kind":"content"}],"seeAlsoSections":[{"title":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting"],"generated":true,"anchor":"시작하기"}],"abstract":[{"type":"text","text":"광고주 SDK를 사용하려면 먼저 광고 계정에 연결된 "},{"code":"Track ID","type":"codeVoice"},{"text":"가 필요합니다.","type":"text"}],"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/gettrackid"]},{"paths":["\/documentation\/kakaoadsdk\/gettrackid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"Track ID 발급받기","modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Article","role":"article"},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID"},"references":{"https://business.kakao.com/pixel":{"titleInlineContent":[{"text":"픽셀 & SDK","type":"text"}],"url":"https:\/\/business.kakao.com\/pixel","identifier":"https:\/\/business.kakao.com\/pixel","type":"link","title":"픽셀 & SDK"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/InstallSDK":{"kind":"article","url":"\/documentation\/kakaoadsdk\/installsdk","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","role":"article","type":"topic","title":"SDK 설치하기"},"https://business.kakao.com":{"titleInlineContent":[{"text":"Kakao Business","type":"text"}],"url":"https:\/\/business.kakao.com","identifier":"https:\/\/business.kakao.com","type":"link","title":"Kakao Business"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","role":"collection","title":"KakaoAd SDK","abstract":[]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProjectSetting":{"url":"\/documentation\/kakaoadsdk\/projectsetting","title":"프로젝트 설정","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"generated":true,"anchor":"시작하기","title":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting"]}],"path":"\/seeAlsoSections","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}