{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK"},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"anchor":"시작하기","generated":true,"title":"시작하기"}],"primaryContentSections":[{"kind":"content","content":[{"level":2,"text":"Swift Package Manager 설치","anchor":"Swift-Package-Manager-%EC%84%A4%EC%B9%98","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Xcode에서 프로젝트를 엽니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"Package Dependencies","type":"codeVoice"},{"text":"를 선택합니다.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"+"},{"type":"text","text":" 버튼을 눌러 패키지 추가 화면을 엽니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"패키지 이름 ","type":"text"},{"code":"KakaoAdPackage","type":"codeVoice"},{"type":"text","text":" 또는 아래 저장소 주소를 입력합니다."}]}]}],"type":"orderedList"},{"inlineContent":[{"type":"codeVoice","code":"https:\/\/github.com\/KakaoAd\/KakaoAdPackage.git"}],"type":"paragraph"},{"type":"heading","anchor":"XCFramework-%EC%88%98%EB%8F%99-%EC%84%A4%EC%B9%98","text":"XCFramework 수동 설치","level":2},{"type":"orderedList","items":[{"content":[{"inlineContent":[{"text":"배포된 ","type":"text"},{"code":"KakaoAdSDK.xcframework.zip","type":"codeVoice"},{"text":"을 다운로드합니다.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"압축을 해제합니다.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"KakaoAdSDK.xcframework","type":"codeVoice"},{"text":"를 앱 프로젝트의 ","type":"text"},{"code":"Frameworks, Libraries, and Embedded Content","type":"codeVoice"},{"text":"에 추가합니다.","type":"text"}]}]}]},{"type":"heading","anchor":"%EC%B0%B8%EA%B3%A0","text":"참고","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"text":"배포 프로세스 2.0 기준으로 ","type":"text"},{"code":"CocoaPods","type":"codeVoice"},{"text":"는 더 이상 공식 배포 채널로 사용하지 않습니다.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"XCFramework"},{"type":"text","text":"를 사용하면 과거 fat framework 방식에서 필요했던 strip 스크립트 후처리가 필요하지 않습니다."}]}]}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/kakaoadsdk\/installsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/installsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","metadata":{"modules":[{"name":"KakaoAd SDK"}],"role":"article","title":"SDK 설치하기","roleHeading":"Article"},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProjectSetting":{"abstract":[],"title":"프로젝트 설정","url":"\/documentation\/kakaoadsdk\/projectsetting","kind":"article","role":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/GetTrackID":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","role":"article","abstract":[{"type":"text","text":"광고주 SDK를 사용하려면 먼저 광고 계정에 연결된 "},{"code":"Track ID","type":"codeVoice"},{"type":"text","text":"가 필요합니다."}],"title":"Track ID 발급받기","type":"topic","url":"\/documentation\/kakaoadsdk\/gettrackid"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/RequestIDFA":{"url":"\/documentation\/kakaoadsdk\/requestidfa","type":"topic","role":"article","title":"IDFA 추적 권한 요청","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","kind":"article","abstract":[{"type":"text","text":"광고 성과 측정을 정확하게 수행하려면 앱의 추적 권한 요청 시점과 SDK 활성화 시점을 함께 고려해야 합니다."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"anchor":"시작하기","title":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"generated":true}],"op":"replace"}]}]}