{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"sections":[],"abstract":[{"type":"text","text":"이벤트 수집을 위한 기본 클래스"},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다."},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","doc:\/\/com.kakao.biz.KakaoAdSDK\/SH"],"type":"conformsTo"}],"seeAlsoSections":[{"title":"핵심 타입","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"],"anchor":"핵심-타입"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"KakaoAdTracker"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker","role":"symbol","title":"KakaoAdTracker","modules":[{"name":"KakaoAd SDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdTracker"}]},"topicSections":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId"],"anchor":"Type-Properties"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:currency:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:currency:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendCompleteRegisterEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendLoginEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendMissionCompleteEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendParticipationEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPreparationEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSearchEvent(tag:searchString:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSignUpEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendTutorialEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewCartEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)"],"anchor":"Type-Methods"}],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewCartEvent(tag:)":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewCartEvent(tag:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendViewCartEventWithTag:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendViewCartEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcartevent(tag:)","title":"sendViewCartEvent(tag:)","abstract":[{"type":"text","text":"장바구니 보기 이벤트"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP"},"doc://com.kakao.biz.KakaoAdSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToWishListEvent(tag:contentId:)":{"kind":"symbol","title":"sendAddToWishListEvent(tag:contentId:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToWishListEventWithTag:contentId:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendAddToWishListEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tag"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contentId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"deprecated":true,"role":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:contentid:)","abstract":[{"text":"관심상품 추가 이벤트","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:contentId:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendCompleteRegisterEvent(tag:)":{"kind":"symbol","abstract":[{"type":"text","text":"회원가입 이벤트"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendCompleteRegisterEventWithTag:"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendcompleteregisterevent(tag:)","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendCompleteRegisterEvent(tag:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendCompleteRegisterEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"title":"sendCompleteRegisterEvent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/trackId":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId","navigatorTitle":[{"kind":"identifier","text":"trackId"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/trackid","title":"trackId","abstract":[{"type":"text","text":"광고계정별로 고유한 식별값."},{"type":"text","text":" "},{"type":"text","text":"trackId 를 설정하지 않을 경우 이벤트 수집은 이루어지지 않습니다."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewContentEvent(tag:currency:products:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:currency:products:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:currency:products:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendViewContentEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"products","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"KakaoAdDetailProduct","kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"type":"topic","title":"sendViewContentEvent(tag:currency:products:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendLoginEvent(tag:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendLoginEventWithTag:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendloginevent(tag:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendLoginEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"로그인 이벤트"}],"title":"sendLoginEvent(tag:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendLoginEvent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/activate()":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/activate()","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"activate","kind":"identifier"}],"type":"topic","role":"symbol","title":"activate()","kind":"symbol","abstract":[{"text":"이벤트 트래커 활성화","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToCartEvent(tag:contentId:)":{"abstract":[{"type":"text","text":"장바구니 추가 이벤트"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAddToCartEvent"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tag"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"contentId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:contentid:)","title":"sendAddToCartEvent(tag:contentId:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","deprecated":true},"doc://com.kakao.biz.KakaoAdSDK/SH":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendParticipationEvent(tag:)":{"title":"sendParticipationEvent(tag:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendParticipationEvent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendParticipationEventWithTag:","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendparticipationevent(tag:)","role":"symbol","abstract":[{"type":"text","text":"잠재고객 이벤트"}],"kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendParticipationEvent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendMissionCompleteEvent(tag:)":{"type":"topic","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendMissionCompleteEvent(tag:)","title":"sendMissionCompleteEvent(tag:)","kind":"symbol","abstract":[{"type":"text","text":"목표달성"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendmissioncompleteevent(tag:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendMissionCompleteEvent"},{"kind":"text","text":"("},{"text":"tag","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendMissionCompleteEventWithTag:"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendPreparationEvent(tag:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendPreparationEventWithTag:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpreparationevent(tag:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPreparationEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"사전준비 이벤트"}],"type":"topic","title":"sendPreparationEvent(tag:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPreparationEvent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendTutorialEvent(tag:)":{"abstract":[{"text":"튜토리얼 이벤트","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendTutorialEventWithTag:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendtutorialevent(tag:)","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendTutorialEvent(tag:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendTutorialEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"sendTutorialEvent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"title":"KakaoAdDetailProduct","role":"symbol","abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"text":" ","type":"text"},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/s7CVarArgP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpurchaseevent(tag:totalquantity:totalprice:currency:transactionid:products:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPurchaseEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"totalQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"transactionId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"text":"KakaoAdDetailProduct","kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct"},{"text":"])","kind":"text"}],"abstract":[{"text":"구매 이벤트","type":"text"}],"type":"topic","title":"sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewContentEvent(tag:contentId:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:contentId:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:contentid:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendViewContentEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contentId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"type":"topic","title":"sendViewContentEvent(tag:contentId:)","kind":"symbol","role":"symbol","deprecated":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:contentId:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToWishListEvent(tag:currency:products:)":{"kind":"symbol","title":"sendAddToWishListEvent(tag:currency:products:)","navigatorTitle":[{"kind":"text","text":"+ "},{"text":"sendAddToWishListEventWithTag:currency:products:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sendAddToWishListEvent","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"KakaoAdDetailProduct","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct"},{"text":"])","kind":"text"}],"role":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:currency:products:)","abstract":[{"text":"관심상품 추가 이벤트","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:currency:products:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/init":{"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/init","kind":"symbol","title":"init"},"doc://com.kakao.biz.KakaoAdSDK/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendSearchEvent(tag:searchString:)":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendSearchEventWithTag:searchString:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSearchEvent(tag:searchString:)","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendsearchevent(tag:searchstring:)","abstract":[{"text":"Search Event","type":"text"}],"type":"topic","role":"symbol","title":"sendSearchEvent(tag:searchString:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendSearchEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"searchString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendSignUpEvent(tag:)":{"kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSignUpEvent(tag:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendSignUpEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"서비스신청 이벤트"}],"title":"sendSignUpEvent(tag:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendSignUpEventWithTag:"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendsignupevent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToCartEvent(tag:currency:products:)":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToCartEventWithTag:currency:products:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:currency:products:)","abstract":[{"text":"장바구니 추가 이벤트","type":"text"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:currency:products:)","type":"topic","role":"symbol","title":"sendAddToCartEvent(tag:currency:products:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendAddToCartEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"products","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"KakaoAdDetailProduct","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"KakaoAdTracker","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/init"],"title":"Instance Methods"},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId"],"generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:currency:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:currency:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendCompleteRegisterEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendLoginEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendMissionCompleteEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendParticipationEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPreparationEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSearchEvent(tag:searchString:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSignUpEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendTutorialEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewCartEvent(tag:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:contentId:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)"],"anchor":"Type-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"핵심-타입","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"],"title":"핵심 타입","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewCartEvent(tag:)\/title","value":"sendViewCartEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewCartEvent(tag:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendViewCartEventWithTag:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:contentId:)\/title","value":"sendAddToWishListEventWithTag:contentId:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:contentId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:contentId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendCompleteRegisterEvent(tag:)\/title","op":"replace","value":"sendCompleteRegisterEventWithTag:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendCompleteRegisterEvent(tag:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendCompleteRegisterEventWithTag:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/title","op":"replace","value":"trackId"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/fragments","op":"replace","value":[{"kind":"identifier","text":"trackId"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/title","op":"replace","value":"sendViewContentEventWithTag:currency:products:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendViewContentEventWithTag:currency:products:"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendLoginEvent(tag:)\/title","op":"replace","value":"sendLoginEventWithTag:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendLoginEvent(tag:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendLoginEventWithTag:"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/title","op":"replace","value":"activate"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"activate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/title","op":"replace","value":"sendAddToCartEventWithTag:contentId:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","op":"replace","value":"KakaoAdTracker"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendParticipationEvent(tag:)\/title","value":"sendParticipationEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendParticipationEvent(tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendParticipationEventWithTag:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendMissionCompleteEvent(tag:)\/title","value":"sendMissionCompleteEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendMissionCompleteEvent(tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendMissionCompleteEventWithTag:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPreparationEvent(tag:)\/title","value":"sendPreparationEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPreparationEvent(tag:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendPreparationEventWithTag:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendTutorialEvent(tag:)\/title","value":"sendTutorialEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendTutorialEvent(tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendTutorialEventWithTag:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title","value":"KakaoAdDetailProduct"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)\/title","value":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:contentId:)\/title","value":"sendViewContentEventWithTag:contentId:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:contentId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:contentId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:currency:products:)\/title","value":"sendAddToWishListEventWithTag:currency:products:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:currency:products:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:currency:products:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSearchEvent(tag:searchString:)\/title","value":"sendSearchEventWithTag:searchString:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSearchEvent(tag:searchString:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendSearchEventWithTag:searchString:","kind":"identifier"}]},{"value":"sendSignUpEventWithTag:","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSignUpEvent(tag:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"sendSignUpEventWithTag:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSignUpEvent(tag:)\/fragments"},{"value":"sendAddToCartEventWithTag:currency:products:","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:currency:products:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToCartEventWithTag:currency:products:"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:currency:products:)\/fragments"}]}]}