{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"},"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","role":"symbol","modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Class","title":"KakaoAdDetailProduct","navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"anchor":"모델-및-참고","title":"모델 및 참고","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoaddetailproduct"]}],"sections":[],"abstract":[{"type":"text","text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입"},{"type":"text","text":" "},{"type":"text","text":"상품명, 수량, 가격 정보를 가지고 있습니다."}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(id:name:quantity:price:brand:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(name:quantity:price:)"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/dictionaryRepresentation()"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","doc:\/\/com.kakao.biz.KakaoAdSDK\/SH"],"kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"mentions":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail"],"kind":"mentions"}],"references":{"doc://com.kakao.biz.KakaoAdSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ"},"doc://com.kakao.biz.KakaoAdSDK/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject"},"doc://com.kakao.biz.KakaoAdSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SH"},"doc://com.kakao.biz.KakaoAdSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProductDetail":{"role":"article","abstract":[{"code":"KakaoAdDetailProduct","type":"codeVoice"},{"text":"는 구매, 관심상품 추가, 장바구니 추가, 콘텐츠 또는 상품 조회 이벤트에서 사용하는 상품 상세 정보 타입입니다.","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","url":"\/documentation\/kakaoadsdk\/productdetail","title":"상품 상세 정보","kind":"article","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","abstract":[{"type":"text","text":"이벤트 수집을 위한 기본 클래스"},{"type":"text","text":" "},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다."}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KakaoAdTracker"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","title":"KakaoAdTracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"type":"text","text":" "},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"title":"KakaoAdDetailProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdDetailProduct","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","type":"topic","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/s7CVarArgP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct/init(name:quantity:price:)":{"url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/init(name:quantity:price:)","title":"init(name:quantity:price:)","navigatorTitle":[{"text":"- ","kind":"text"},{"text":"initWithName:quantity:price:","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(name:quantity:price:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"price","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"구매 이벤트를 전송할 때 Producs 파라메터의 세부 항목을 생성합니다. 구매 이벤트의 Products 파라메터는 Array고","type":"text"},{"text":" ","type":"text"},{"text":"그 세부 항목의 타입은 KakaoAdDetailProduct 입니다.","type":"text"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct/dictionaryRepresentation()":{"kind":"symbol","type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/dictionaryrepresentation()","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/dictionaryRepresentation()","role":"symbol","title":"dictionaryRepresentation()","abstract":[{"text":"해당 인스턴스의 프로퍼티 값들을 딕셔너리로 반환합니다. 값들의 키값은 프로퍼티 명과 동일하고, 값들의 타입은 모두 문자열입니다.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct/init(id:name:quantity:price:brand:)":{"navigatorTitle":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:name:quantity:price:brand:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"quantity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"price","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"brand"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(id:name:quantity:price:brand:)","abstract":[{"type":"text","text":"구매 이벤트를 전송할 때 Producs 파라메터의 세부 항목을 생성합니다. 구매 이벤트의 Products 파라메터는 Array고"},{"type":"text","text":" "},{"type":"text","text":"그 세부 항목의 타입은 KakaoAdDetailProduct 입니다."}],"role":"symbol","kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct\/init(id:name:quantity:price:brand:)","title":"init(id:name:quantity:price:brand:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"KakaoAdDetailProduct"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/dictionaryRepresentation()","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(id:name:quantity:price:brand:)","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct\/init(name:quantity:price:)"],"generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"모델 및 참고","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"],"generated":true,"anchor":"모델-및-참고"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdDetailProduct","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","op":"replace","value":"KakaoAdTracker"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title","op":"replace","value":"KakaoAdDetailProduct"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments","op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(name:quantity:price:)\/title","op":"replace","value":"initWithName:quantity:price:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(name:quantity:price:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithName:quantity:price:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1dictionaryRepresentation()\/title","op":"replace","value":"dictionaryRepresentation"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1dictionaryRepresentation()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dictionaryRepresentation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(id:name:quantity:price:brand:)\/title","op":"replace","value":"initWithId:name:quantity:price:brand:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct~1init(id:name:quantity:price:brand:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithId:name:quantity:price:brand:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}