{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","doc:\/\/com.kakao.biz.KakaoAdSDK\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@KakaoAdSDK@objc(cs)LogChecker","roleHeading":"Class","modules":[{"name":"KakaoAd SDK"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"}],"navigatorTitle":[{"text":"LogChecker","kind":"identifier"}],"role":"symbol","title":"LogChecker"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/logchecker"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/logchecker"]}],"topicSections":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/openLogConsole()"],"generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker"},"kind":"symbol","references":{"doc://com.kakao.biz.KakaoAdSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker/openLogConsole()":{"type":"topic","url":"\/documentation\/kakaoadsdk\/logchecker\/openlogconsole()","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"openLogConsole","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"openLogConsole"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/openLogConsole()","kind":"symbol","title":"openLogConsole()"},"doc://com.kakao.biz.KakaoAdSDK/SH":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ"},"doc://com.kakao.biz.KakaoAdSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker":{"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"}],"navigatorTitle":[{"text":"LogChecker","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker","url":"\/documentation\/kakaoadsdk\/logchecker","title":"LogChecker"},"doc://com.kakao.biz.KakaoAdSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/LogChecker/init":{"url":"\/documentation\/kakaoadsdk\/logchecker\/init","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/init","abstract":[],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"LogChecker","path":"\/metadata\/title","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"LogChecker"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"LogChecker"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/init"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/LogChecker\/openLogConsole()"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogChecker","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}},{"value":"openLogConsole","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker~1openLogConsole()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"openLogConsole"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker~1openLogConsole()\/fragments","op":"replace"},{"value":"LogChecker","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LogChecker"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/fragments","op":"replace"},{"value":[{"text":"LogChecker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1LogChecker\/navigatorTitle","op":"replace"}]}]}