{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","doc:\/\/com.kakao.biz.KakaoAdSDK\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}],"metadata":{"externalID":"c:@M@KakaoAdSDK@objc(cs)Logger","roleHeading":"Class","modules":[{"name":"KakaoAd SDK"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"kind":"identifier","text":"Logger"}],"role":"symbol","title":"Logger"},"sections":[],"variants":[{"paths":["\/documentation\/kakaoadsdk\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/debug(_:fileName:functionName:line:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"},"kind":"symbol","references":{"doc://com.kakao.biz.KakaoAdSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kakao.biz.KakaoAdSDK/SQ":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger":{"title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/logger","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger/debug(_:fileName:functionName:line:)":{"title":"debug(_:fileName:functionName:line:)","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/kakaoadsdk\/logger\/debug(_:filename:functionname:line:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"debug:fileName:functionName:line:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"functionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"line"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/debug(_:fileName:functionName:line:)","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.kakao.biz.KakaoAdSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.kakao.biz.KakaoAdSDK/SH":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.kakao.biz.KakaoAdSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger/init":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/init","url":"\/documentation\/kakaoadsdk\/logger\/init","abstract":[],"type":"topic","role":"symbol","title":"init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"Logger","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Logger"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Logger"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/debug(_:fileName:functionName:line:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/title","value":"Logger","op":"replace"},{"value":[{"kind":"identifier","text":"Logger"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/fragments"},{"value":[{"text":"Logger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/navigatorTitle"},{"value":"debug:fileName:functionName:line:","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger~1debug(_:fileName:functionName:line:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"debug:fileName:functionName:line:"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger~1debug(_:fileName:functionName:line:)\/fragments"}]}]}