{"metadata":{"roleHeading":"Article","modules":[{"name":"KakaoAd SDK"}],"title":"상품 상세 정보","role":"article"},"sections":[],"variants":[{"paths":["\/documentation\/kakaoadsdk\/productdetail"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/productdetail"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"KakaoAdDetailProduct"},{"text":"는 구매, 관심상품 추가, 장바구니 추가, 콘텐츠 또는 상품 조회 이벤트에서 사용하는 상품 상세 정보 타입입니다.","type":"text"}],"seeAlsoSections":[{"anchor":"모델-및-참고","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"],"title":"모델 및 참고","generated":true}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"primaryContentSections":[{"content":[{"anchor":"%ED%8F%AC%ED%95%A8-%EA%B0%80%EB%8A%A5%ED%95%9C-%EA%B0%92","text":"포함 가능한 값","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"id"},{"type":"text","text":": 상품 ID, 선택 값"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"name"},{"type":"text","text":": 상품명, 선택 값"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"quantity"},{"type":"text","text":": 상품 수량, 필수 값"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"price"},{"type":"text","text":": 상품 가격, 필수 값"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"brand"},{"type":"text","text":": 상품 브랜드, 선택 값"}],"type":"paragraph"}]}]},{"anchor":"%EB%B3%80%EA%B2%BD-%EC%82%AC%ED%95%AD","text":"변경 사항","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"0.8.0부터 "},{"type":"codeVoice","code":"brand"},{"type":"text","text":" 프로퍼티가 추가되었습니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"0.8.0부터 구매 이벤트뿐 아니라 장바구니 추가, 관심상품 추가, 콘텐츠 또는 상품 조회 이벤트에서도 사용할 수 있습니다."}],"type":"paragraph"}]}]},{"anchor":"%EC%98%88%EC%8B%9C","text":"예시","type":"heading","level":2},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"syntax":"swift","type":"codeListing","code":["let product = KakaoAdDetailProduct(","    id: \"product-id\",","    name: \"상품명\",","    quantity: 2,","    price: 50000,","    brand: \"브랜드명\"",")"]}]},{"title":"Objective-C","content":[{"syntax":"objective-c","type":"codeListing","code":["KakaoAdDetailProduct *product =","[[KakaoAdDetailProduct alloc] initWithId:@\"product-id\"","                                    name:@\"상품명\"","                                quantity:2","                                   price:50000","                                   brand:@\"브랜드명\"];"]}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-API","text":"관련 API","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"}]}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C","text":"관련 문서","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","isActive":true}]}]}]}],"kind":"content"}],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","abstract":[{"type":"text","text":"이벤트 수집을 위한 기본 클래스"},{"type":"text","text":" "},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다."}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KakaoAdTracker"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","title":"KakaoAdTracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"type":"text","text":" "},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"title":"KakaoAdDetailProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdDetailProduct","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","type":"topic","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct"],"generated":true,"anchor":"모델-및-참고","title":"모델 및 참고"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","value":"KakaoAdTracker","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title","value":"KakaoAdDetailProduct","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}