{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting"},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"anchor":"시작하기","title":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"generated":true}],"primaryContentSections":[{"content":[{"text":"ATS 설정 검토","anchor":"ATS-%EC%84%A4%EC%A0%95-%EA%B2%80%ED%86%A0","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"iOS는 기본적으로 "},{"type":"codeVoice","code":"ATS(App Transport Security)"},{"type":"text","text":"를 사용하며 HTTPS 통신을 권장합니다."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"광고주 SDK 자체는 ATS 활성화 상태에서도 동작하지만, 광고를 통해 연결되는 외부 페이지는 HTTPS를 항상 보장하지 않을 수 있습니다."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"앱 정책에 따라 필요하면 "},{"type":"codeVoice","code":"Info.plist"},{"type":"text","text":"의 네트워크 관련 예외 설정을 검토하세요."}],"type":"paragraph"},{"code":["<key>NSAppTransportSecurity<\/key>","<dict>","    <key>NSAllowsArbitraryLoads<\/key>","    <true\/>","<\/dict>"],"syntax":"xml","type":"codeListing"},{"level":2,"anchor":"%EC%A3%BC%EC%9D%98","text":"주의","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"이 설정은 앱 전체 네트워크 정책에 영향을 줄 수 있으므로, 실제 앱 정책과 보안 요구사항을 함께 검토한 뒤 적용해야 합니다."}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/kakaoadsdk\/projectsetting"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/projectsetting"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","metadata":{"roleHeading":"Article","role":"article","modules":[{"name":"KakaoAd SDK"}],"title":"프로젝트 설정"},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/InstallSDK":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","role":"article","abstract":[],"title":"SDK 설치하기","type":"topic","url":"\/documentation\/kakaoadsdk\/installsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/GetTrackID":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","role":"article","abstract":[{"type":"text","text":"광고주 SDK를 사용하려면 먼저 광고 계정에 연결된 "},{"code":"Track ID","type":"codeVoice"},{"type":"text","text":"가 필요합니다."}],"title":"Track ID 발급받기","type":"topic","url":"\/documentation\/kakaoadsdk\/gettrackid"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/RequestIDFA":{"url":"\/documentation\/kakaoadsdk\/requestidfa","type":"topic","role":"article","title":"IDFA 추적 권한 요청","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","kind":"article","abstract":[{"type":"text","text":"광고 성과 측정을 정확하게 수행하려면 앱의 추적 권한 요청 시점과 SDK 활성화 시점을 함께 고려해야 합니다."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"anchor":"시작하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"title":"시작하기","generated":true}],"path":"\/seeAlsoSections"}]}]}