{"metadata":{"role":"article","modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Article","title":"IDFA 추적 권한 요청"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"abstract":[{"type":"text","text":"광고 성과 측정을 정확하게 수행하려면 앱의 추적 권한 요청 시점과 SDK 활성화 시점을 함께 고려해야 합니다."}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"anchor":"시작하기","title":"시작하기"}],"primaryContentSections":[{"content":[{"level":2,"type":"heading","text":"권장 순서","anchor":"%EA%B6%8C%EC%9E%A5-%EC%88%9C%EC%84%9C"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"ATTrackingManager.requestTrackingAuthorization(_:)","type":"codeVoice"},{"type":"text","text":"를 호출합니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"사용자의 응답을 확인합니다."}]}]},{"content":[{"inlineContent":[{"text":"이후 ","type":"text"},{"code":"KakaoAdTracker.activate()","type":"codeVoice"},{"text":"를 호출합니다.","type":"text"}],"type":"paragraph"}]}],"type":"orderedList"},{"type":"heading","anchor":"%EC%A3%BC%EC%9D%98","text":"주의","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"추적 권한 요청 전에 SDK를 활성화하면 설치 이벤트가 누락될 수 있습니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"앱의 권한 요청 정책과 심사 대응 문구는 별도로 관리해야 합니다."}]}]}],"type":"unorderedList"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/kakaoadsdk\/requestidfa"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/requestidfa"]}],"kind":"article","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","role":"collection","abstract":[],"title":"KakaoAd SDK","type":"topic","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/GetTrackID":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","role":"article","abstract":[{"type":"text","text":"광고주 SDK를 사용하려면 먼저 광고 계정에 연결된 "},{"code":"Track ID","type":"codeVoice"},{"type":"text","text":"가 필요합니다."}],"title":"Track ID 발급받기","type":"topic","url":"\/documentation\/kakaoadsdk\/gettrackid"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/InstallSDK":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","role":"article","abstract":[],"title":"SDK 설치하기","type":"topic","url":"\/documentation\/kakaoadsdk\/installsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProjectSetting":{"abstract":[],"title":"프로젝트 설정","url":"\/documentation\/kakaoadsdk\/projectsetting","kind":"article","role":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":[{"title":"시작하기","anchor":"시작하기","generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/GetTrackID","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/InstallSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProjectSetting","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"]}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}