{"metadata":{"modules":[{"name":"KakaoAd SDK"}],"title":"콘텐츠 또는 상품 조회 이벤트 전송","roleHeading":"Article","role":"article"},"sections":[],"variants":[{"paths":["\/documentation\/kakaoadsdk\/sendviewcontentevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/sendviewcontentevent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"seeAlsoSections":[{"title":"연동하기","generated":true,"anchor":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"0.7.8 이하: "},{"type":"codeVoice","code":"tag"},{"type":"text","text":", "},{"type":"codeVoice","code":"contentId"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"0.8.0 이상: "},{"type":"codeVoice","code":"tag"},{"type":"text","text":", "},{"type":"codeVoice","code":"currency"},{"type":"text","text":", "},{"type":"codeVoice","code":"products"}],"type":"paragraph"}]}]},{"anchor":"%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0","type":"heading","level":2,"text":"파라미터"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"codeVoice","code":"tag"},{"type":"text","text":": 한 광고계정 내에서 같은 이벤트 코드에서도 특별한 분류가 필요할 때 사용하는 값"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"currency"},{"type":"text","text":": 결제 금액 통화, ISO 4217 형식, 비어 있으면 기본값 "},{"type":"codeVoice","code":"KRW"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"codeVoice","code":"products"},{"type":"text","text":": 조회된 상품 목록"}],"type":"paragraph"}]}]},{"anchor":"080-%EC%9D%B4%EC%83%81","type":"heading","level":2,"text":"0.8.0 이상"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"code":["let tag = \"tag\"","let currency = \"KRW\"","let product1 = KakaoAdDetailProduct(id: \"product-1\", name: \"상품1\", quantity: 1, price: 10000)","let product2 = KakaoAdDetailProduct(id: \"product-2\", name: \"상품2\", quantity: 2, price: 5000, brand: \"브랜드명\")","","KakaoAdTracker.sendViewContentEvent(tag: tag, currency: currency, products: [product1, product2])"],"type":"codeListing","syntax":"swift"}]},{"title":"Objective-C","content":[{"code":["NSString *tag = @\"tag\";","NSString *currency = @\"KRW\";","KakaoAdDetailProduct *product1 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-1\" name:@\"상품1\" quantity:1 price:10000];","KakaoAdDetailProduct *product2 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-2\" name:@\"상품2\" quantity:2 price:5000 brand:@\"브랜드명\"];","","[KakaoAdTracker sendViewContentEventWithTag:tag currency:currency products:@[product1, product2]];"],"type":"codeListing","syntax":"objective-c"}]}]},{"anchor":"078-%EC%9D%B4%ED%95%98","type":"heading","level":2,"text":"0.7.8 이하"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"code":["let tag = \"tag\"","let contentId = \"contentId\"","KakaoAdTracker.sendViewContentEvent(tag: tag, contentId: contentId)"],"type":"codeListing","syntax":"swift"}]},{"title":"Objective-C","content":[{"code":["NSString *tag = @\"tag\";","NSString *contentId = @\"contentId\";","[KakaoAdTracker sendViewContentEventWithTag:tag contentId:contentId];"],"type":"codeListing","syntax":"objective-c"}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-API","type":"heading","level":2,"text":"관련 API"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:contentId:)","isActive":true}],"type":"paragraph"}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C","type":"heading","level":2,"text":"관련 문서"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","isActive":true}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog","isActive":true}],"type":"paragraph"}]}]}]}],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProductDetail":{"role":"article","abstract":[{"code":"KakaoAdDetailProduct","type":"codeVoice"},{"text":"는 구매, 관심상품 추가, 장바구니 추가, 콘텐츠 또는 상품 조회 이벤트에서 사용하는 상품 상세 정보 타입입니다.","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","url":"\/documentation\/kakaoadsdk\/productdetail","title":"상품 상세 정보","kind":"article","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewContentEvent(tag:contentId:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:contentid:)","title":"sendViewContentEvent(tag:contentId:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendViewContentEventWithTag:contentId:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:contentId:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendViewContentEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"role":"symbol","deprecated":true},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSignUpEvent":{"url":"\/documentation\/kakaoadsdk\/sendsignupevent","title":"서비스신청 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendCompleteRegisterEvent":{"role":"article","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","title":"회원가입 이벤트 전송","url":"\/documentation\/kakaoadsdk\/sendcompleteregisterevent","type":"topic","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewContentEvent(tag:currency:products:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:currency:products:)","title":"sendViewContentEvent(tag:currency:products:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:currency:products:","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendViewContentEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"products","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ChangeLog":{"url":"\/documentation\/kakaoadsdk\/changelog","title":"변경 사항","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"anchor":"연동하기","generated":true}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:contentId:)\/title","op":"replace","value":"sendViewContentEventWithTag:contentId:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:contentId:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:contentId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/title","op":"replace","value":"sendViewContentEventWithTag:currency:products:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:currency:products:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}