{"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"KakaoAd SDK"}],"title":"장바구니 추가 이벤트 전송","roleHeading":"Article","role":"article"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"title":"연동하기","generated":true,"anchor":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"]}],"variants":[{"paths":["\/documentation\/kakaoadsdk\/sendaddtocartevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/sendaddtocartevent"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0.7.8 이하: "},{"code":"tag","type":"codeVoice"},{"type":"text","text":", "},{"code":"contentId","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0.8.0 이상: "},{"code":"tag","type":"codeVoice"},{"type":"text","text":", "},{"code":"currency","type":"codeVoice"},{"type":"text","text":", "},{"code":"products","type":"codeVoice"}]}]}]},{"anchor":"%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0","type":"heading","level":2,"text":"파라미터"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"tag","type":"codeVoice"},{"type":"text","text":": 한 광고계정 내에서 같은 이벤트 코드에서도 특별한 분류가 필요할 때 사용하는 값"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"currency","type":"codeVoice"},{"type":"text","text":": 결제 금액 통화, ISO 4217 형식, 비어 있으면 기본값 "},{"code":"KRW","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"products","type":"codeVoice"},{"type":"text","text":": 장바구니에 추가된 상품 목록"}]}]}]},{"anchor":"080-%EC%9D%B4%EC%83%81","type":"heading","level":2,"text":"0.8.0 이상"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["let tag = \"tag\"","let currency = \"KRW\"","let product1 = KakaoAdDetailProduct(id: \"product-1\", name: \"상품1\", quantity: 1, price: 10000)","let product2 = KakaoAdDetailProduct(id: \"product-2\", name: \"상품2\", quantity: 2, price: 5000, brand: \"브랜드명\")","","KakaoAdTracker.sendAddToCartEvent(tag: tag, currency: currency, products: [product1, product2])"]}]},{"title":"Objective-C","content":[{"type":"codeListing","syntax":"objective-c","code":["NSString *tag = @\"tag\";","NSString *currency = @\"KRW\";","KakaoAdDetailProduct *product1 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-1\" name:@\"상품1\" quantity:1 price:10000];","KakaoAdDetailProduct *product2 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-2\" name:@\"상품2\" quantity:2 price:5000 brand:@\"브랜드명\"];","","[KakaoAdTracker sendAddToCartEventWithTag:tag currency:currency products:@[product1, product2]];"]}]}]},{"anchor":"078-%EC%9D%B4%ED%95%98","type":"heading","level":2,"text":"0.7.8 이하"},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["let tag = \"tag\"","let contentId = \"contentId\"","KakaoAdTracker.sendAddToCartEvent(tag: tag, contentId: contentId)"]}]},{"title":"Objective-C","content":[{"type":"codeListing","syntax":"objective-c","code":["NSString *tag = @\"tag\";","NSString *contentId = @\"contentId\";","[KakaoAdTracker sendAddToCartEventWithTag:tag contentId:contentId];"]}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-API","type":"heading","level":2,"text":"관련 API"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:currency:products:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)"}]}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C","type":"heading","level":2,"text":"관련 문서"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog"}]}]}]}]}],"kind":"article","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ChangeLog":{"url":"\/documentation\/kakaoadsdk\/changelog","title":"변경 사항","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSignUpEvent":{"url":"\/documentation\/kakaoadsdk\/sendsignupevent","title":"서비스신청 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendCompleteRegisterEvent":{"role":"article","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","title":"회원가입 이벤트 전송","url":"\/documentation\/kakaoadsdk\/sendcompleteregisterevent","type":"topic","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProductDetail":{"role":"article","abstract":[{"code":"KakaoAdDetailProduct","type":"codeVoice"},{"text":"는 구매, 관심상품 추가, 장바구니 추가, 콘텐츠 또는 상품 조회 이벤트에서 사용하는 상품 상세 정보 타입입니다.","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","url":"\/documentation\/kakaoadsdk\/productdetail","title":"상품 상세 정보","kind":"article","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToCartEvent(tag:currency:products:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:currency:products:)","title":"sendAddToCartEvent(tag:currency:products:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToCartEventWithTag:currency:products:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:currency:products:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAddToCartEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"장바구니 추가 이벤트"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToCartEvent(tag:contentId:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:contentid:)","title":"sendAddToCartEvent(tag:contentId:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sendAddToCartEventWithTag:contentId:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendAddToCartEvent"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"contentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","abstract":[{"text":"장바구니 추가 이벤트","type":"text"}],"role":"symbol","deprecated":true}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"generated":true,"anchor":"연동하기"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:currency:products:)\/title","op":"replace","value":"sendAddToCartEventWithTag:currency:products:"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:currency:products:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToCartEventWithTag:currency:products:"}]},{"value":"sendAddToCartEventWithTag:contentId:","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}