{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent"},"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"KakaoAd SDK"}],"title":"구매 이벤트 전송"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"anchor":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"title":"연동하기","generated":true}],"variants":[{"paths":["\/documentation\/kakaoadsdk\/sendpurchaseevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/sendpurchaseevent"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"content":[{"text":"파라미터","anchor":"%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"tag"},{"type":"text","text":": 한 광고계정 내에서 같은 이벤트 코드에서도 특별한 분류가 필요할 때 사용하는 값"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"totalQuantity","type":"codeVoice"},{"text":": 주문에 포함된 상품 수","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"totalPrice"},{"type":"text","text":": 주문 전체 금액"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"currency","type":"codeVoice"},{"type":"text","text":": 결제 금액 통화, ISO 4217 형식"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"transactionId","type":"codeVoice"},{"type":"text","text":": 주문번호처럼 구매를 식별하는 고유 ID, 0.8.1부터 지원"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"products"},{"type":"text","text":": 개별 주문 상품 목록"}]}]}],"type":"unorderedList"},{"text":"변경 사항","anchor":"%EB%B3%80%EA%B2%BD-%EC%82%AC%ED%95%AD","type":"heading","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0.8.1부터 "},{"code":"transactionId","type":"codeVoice"},{"type":"text","text":" 파라미터가 추가되었습니다."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"0.8.0부터 ","type":"text"},{"code":"KakaoAdDetailProduct.brand","type":"codeVoice"},{"text":"를 사용할 수 있습니다.","type":"text"}]}]}],"type":"unorderedList"},{"text":"현재 방식","anchor":"%ED%98%84%EC%9E%AC-%EB%B0%A9%EC%8B%9D","type":"heading","level":2},{"type":"tabNavigator","tabs":[{"title":"Swift","content":[{"type":"codeListing","syntax":"swift","code":["let product1 = KakaoAdDetailProduct(id: \"product-1\", name: \"상품1\", quantity: 1, price: 10000)","let product2 = KakaoAdDetailProduct(id: \"product-2\", name: \"상품2\", quantity: 2, price: 5000, brand: \"브랜드명\")","","KakaoAdTracker.sendPurchaseEvent(","    tag: \"tag\",","    totalQuantity: 3,","    totalPrice: 20000,","    currency: \"KRW\",","    transactionId: \"ORD_K000139123\",","    products: [product1, product2]",")"]}]},{"title":"Objective-C","content":[{"type":"codeListing","syntax":"objective-c","code":["KakaoAdDetailProduct *product1 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-1\" name:@\"상품1\" quantity:1 price:10000];","KakaoAdDetailProduct *product2 = [[KakaoAdDetailProduct alloc] initWithId:@\"product-2\" name:@\"상품2\" quantity:2 price:5000 brand:@\"브랜드명\"];","","[KakaoAdTracker sendPurchaseEventWithTag:@\"tag\"","                           totalQuantity:3","                              totalPrice:20000","                                currency:@\"KRW\"","                           transactionId:@\"ORD_K000139123\"","                                 products:@[product1, product2]];"]}]}]},{"level":2,"type":"heading","anchor":"080-%EC%9D%B4%ED%95%98-%EB%B0%A9%EC%8B%9D","text":"0.8.0 이하 방식"},{"type":"paragraph","inlineContent":[{"code":"transactionId","type":"codeVoice"},{"text":" 없이도 기존 방식으로 계속 호출할 수 있습니다.","type":"text"}]},{"level":2,"type":"heading","anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C","text":"관련 문서"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog","isActive":true}]}]}]},{"text":"관련 API","level":2,"anchor":"%EA%B4%80%EB%A0%A8-API","type":"heading"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"article","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ProductDetail":{"role":"article","abstract":[{"code":"KakaoAdDetailProduct","type":"codeVoice"},{"text":"는 구매, 관심상품 추가, 장바구니 추가, 콘텐츠 또는 상품 조회 이벤트에서 사용하는 상품 상세 정보 타입입니다.","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ProductDetail","url":"\/documentation\/kakaoadsdk\/productdetail","title":"상품 상세 정보","kind":"article","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/ChangeLog":{"url":"\/documentation\/kakaoadsdk\/changelog","title":"변경 사항","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/ChangeLog","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSignUpEvent":{"url":"\/documentation\/kakaoadsdk\/sendsignupevent","title":"서비스신청 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)":{"role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)","abstract":[{"type":"text","text":"구매 이벤트"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpurchaseevent(tag:totalquantity:totalprice:currency:transactionid:products:)","title":"sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPurchaseEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"totalQuantity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalPrice"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"transactionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendCompleteRegisterEvent":{"role":"article","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","title":"회원가입 이벤트 전송","url":"\/documentation\/kakaoadsdk\/sendcompleteregisterevent","type":"topic","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","op":"add","value":null},{"value":[{"generated":true,"anchor":"연동하기","title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"sendPurchaseEventWithTag:totalQuantity:totalPrice:currency:transactionId:products:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPurchaseEvent(tag:totalQuantity:totalPrice:currency:transactionId:products:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}