{"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Article","modules":[{"name":"KakaoAd SDK"}],"role":"article","title":"회원가입 이벤트 전송"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"seeAlsoSections":[{"generated":true,"anchor":"연동하기","title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"]}],"variants":[{"paths":["\/documentation\/kakaoadsdk\/sendcompleteregisterevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/sendcompleteregisterevent"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"content":[{"anchor":"%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0","text":"파라미터","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"tag","type":"codeVoice"},{"text":": 한 광고계정 내에서 같은 이벤트 코드에서도 특별한 분류가 필요할 때 사용하는 값","type":"text"}],"type":"paragraph"}]}]},{"type":"tabNavigator","tabs":[{"content":[{"syntax":"swift","code":["let tag = \"tag\"","KakaoAdTracker.sendCompleteRegisterEvent(tag: tag)"],"type":"codeListing"}],"title":"Swift"},{"content":[{"code":["NSString *tag = @\"tag\";","[KakaoAdTracker sendCompleteRegisterEventWithTag:tag];"],"type":"codeListing","syntax":"objective-c"}],"title":"Objective-C"}]},{"anchor":"%EA%B4%80%EB%A0%A8-API","type":"heading","level":2,"text":"관련 API"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendCompleteRegisterEvent(tag:)"}]}]}],"type":"unorderedList"},{"anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C","type":"heading","level":2,"text":"관련 문서"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"article","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendCompleteRegisterEvent(tag:)":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendCompleteRegisterEvent(tag:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendCompleteRegisterEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendCompleteRegisterEventWithTag:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"회원가입 이벤트"}],"type":"topic","title":"sendCompleteRegisterEvent(tag:)","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendcompleteregisterevent(tag:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSignUpEvent":{"url":"\/documentation\/kakaoadsdk\/sendsignupevent","title":"서비스신청 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"title":"연동하기","anchor":"연동하기"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendCompleteRegisterEvent(tag:)\/title","value":"sendCompleteRegisterEventWithTag:"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendCompleteRegisterEvent(tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendCompleteRegisterEventWithTag:","kind":"identifier"}]}]}]}