{"primaryContentSections":[{"kind":"content","content":[{"type":"heading","anchor":"%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0","text":"파라미터","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"tag","type":"codeVoice"},{"text":": 한 광고계정 내에서 같은 이벤트 코드에서도 특별한 분류가 필요할 때 사용하는 값","type":"text"}]}]}],"type":"unorderedList"},{"type":"heading","text":"권장 태그 예시","level":2,"anchor":"%EA%B6%8C%EC%9E%A5-%ED%83%9C%EA%B7%B8-%EC%98%88%EC%8B%9C"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"SignUp","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"Subscription","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"CardIssuance","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"OpeningAccount","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"code":"LoanApplication","type":"codeVoice"}],"type":"paragraph"}]}]},{"type":"tabNavigator","tabs":[{"content":[{"syntax":"swift","code":["let tag = \"SignUp\"","KakaoAdTracker.sendSignUpEvent(tag: tag)"],"type":"codeListing"}],"title":"Swift"},{"content":[{"syntax":"objective-c","code":["NSString *tag = @\"SignUp\";","[KakaoAdTracker sendSignUpEventWithTag:tag];"],"type":"codeListing"}],"title":"Objective-C"}]},{"type":"heading","text":"관련 API","level":2,"anchor":"%EA%B4%80%EB%A0%A8-API"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSignUpEvent(tag:)","type":"reference","isActive":true}],"type":"paragraph"}]}]},{"type":"heading","text":"관련 문서","level":2,"anchor":"%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%84%9C"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"reference","isActive":true}],"type":"paragraph"}]}]}]}],"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"KakaoAd SDK"}],"title":"서비스신청 이벤트 전송"},"variants":[{"paths":["\/documentation\/kakaoadsdk\/sendsignupevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/sendsignupevent"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","interfaceLanguage":"swift"},"seeAlsoSections":[{"anchor":"연동하기","title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"generated":true}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","role":"collection","title":"KakaoAd SDK","abstract":[]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"url":"\/documentation\/kakaoadsdk\/starteventtracker","title":"Track ID 설정 및 이벤트 트래커 활성화","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","type":"topic","kind":"article","abstract":[{"code":"KakaoAdTracker.trackId","type":"codeVoice"},{"text":"는 필수 입력 값입니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendSignUpEvent(tag:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendsignupevent(tag:)","title":"sendSignUpEvent(tag:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendSignUpEventWithTag:","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendSignUpEvent(tag:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendSignUpEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"서비스신청 이벤트","type":"text"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendCompleteRegisterEvent":{"role":"article","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","title":"회원가입 이벤트 전송","url":"\/documentation\/kakaoadsdk\/sendcompleteregisterevent","type":"topic","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"generated":true,"anchor":"연동하기"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSignUpEvent(tag:)\/title","value":"sendSignUpEventWithTag:","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendSignUpEvent(tag:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendSignUpEventWithTag:"}],"op":"replace"}]}]}