{"sections":[],"metadata":{"title":"Track ID 설정 및 이벤트 트래커 활성화","role":"article","roleHeading":"Article","modules":[{"name":"KakaoAd SDK"}]},"variants":[{"paths":["\/documentation\/kakaoadsdk\/starteventtracker"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/starteventtracker"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"type":"text","text":"는 필수 입력 값입니다."}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"generated":true,"anchor":"연동하기","title":"연동하기"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK"]]},"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"광고주 SDK에서는 ATT 권한 요청 흐름 이후에 ","type":"text"},{"code":"trackId","type":"codeVoice"},{"text":"를 설정하고, 그 다음 ","type":"text"},{"code":"KakaoAdTracker.activate()","type":"codeVoice"},{"text":"를 호출하는 것을 권장합니다.","type":"text"}]},{"anchor":"%EA%B6%8C%EC%9E%A5-%EA%B5%AC%ED%98%84-%EC%88%9C%EC%84%9C","type":"heading","level":2,"text":"권장 구현 순서"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"추적 권한 요청"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"권한 요청 결과를 확인","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"trackId"},{"type":"text","text":" 설정"}]}]},{"content":[{"inlineContent":[{"code":"activate()","type":"codeVoice"},{"type":"text","text":" 호출"}],"type":"paragraph"}]}]},{"anchor":"%EA%B5%AC%ED%98%84-%EC%9B%90%EC%B9%99","text":"구현 원칙","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"code":"trackId","type":"codeVoice"},{"type":"text","text":"는 "},{"code":"activate()","type":"codeVoice"},{"text":" 전에 반드시 설정되어야 합니다.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"ATT 권한 요청을 앱이 active 된 뒤에 수행한다면, "},{"code":"trackId","type":"codeVoice"},{"text":"도 같은 흐름 안에서 함께 설정하는 것이 안전합니다.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"추적 권한 요청 전에 미리 "},{"code":"activate()","type":"codeVoice"},{"type":"text","text":"를 호출하지 않도록 주의합니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"라이프사이클 메서드 자체보다 "},{"code":"ATT 완료 이후에 trackId 설정 -> activate 호출","type":"codeVoice"},{"type":"text","text":" 순서를 지키는 것이 더 중요합니다."}],"type":"paragraph"}]}]},{"anchor":"%EA%B6%8C%EC%9E%A5-%ED%9D%90%EB%A6%84-%EC%98%88%EC%8B%9C","text":"권장 흐름 예시","type":"heading","level":2},{"type":"tabNavigator","tabs":[{"content":[{"code":["\/\/ ATT 권한 요청 완료 후","KakaoAdTracker.trackId = \"Input Your Track ID\"","KakaoAdTracker.activate()"],"syntax":"swift","type":"codeListing"}],"title":"Swift"},{"content":[{"code":["\/\/ ATT 권한 요청 완료 후","KakaoAdTracker.trackId = @\"Input Your Track ID\";","[KakaoAdTracker activate];"],"syntax":"objective-c","type":"codeListing"}],"title":"Objective-C"}]},{"anchor":"%EA%B5%AC%ED%98%84-%EC%9C%84%EC%B9%98%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B0%80%EC%9D%B4%EB%93%9C","text":"구현 위치에 대한 가이드","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"SwiftUI 앱, SceneDelegate 기반 앱, AppDelegate 기반 앱 모두 적용 가능합니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"다만 구체적인 권한 요청 위치는 앱 구조에 따라 달라질 수 있습니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"구체적인 ATT 권한 요청 샘플은 "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA"},{"type":"text","text":" 문서를 참고해 주세요."}],"type":"paragraph"}]}]},{"anchor":"%EA%B4%80%EB%A0%A8-API","text":"관련 API","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()"}],"type":"paragraph"}]}]},{"anchor":"%EB%8B%A4%EC%9D%8C-%EB%8B%A8%EA%B3%84","text":"다음 단계","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent"}],"type":"paragraph"}]}]}]}],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendParticipationEvent":{"url":"\/documentation\/kakaoadsdk\/sendparticipationevent","title":"잠재고객 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPreparationEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","url":"\/documentation\/kakaoadsdk\/sendpreparationevent","role":"article","abstract":[],"type":"topic","title":"사전준비 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewContentEvent":{"type":"topic","abstract":[{"type":"text","text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다."}],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendviewcontentevent","title":"콘텐츠 또는 상품 조회 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/trackId":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/trackid","title":"trackId","navigatorTitle":[{"text":"trackId","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"광고계정별로 고유한 식별값.","type":"text"},{"text":" ","type":"text"},{"text":"trackId 를 설정하지 않을 경우 이벤트 수집은 이루어지지 않습니다.","type":"text"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendViewCartEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","url":"\/documentation\/kakaoadsdk\/sendviewcartevent","role":"article","abstract":[],"type":"topic","title":"장바구니 보기 이벤트 전송","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendTutorialEvent":{"url":"\/documentation\/kakaoadsdk\/sendtutorialevent","title":"튜토리얼 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSignUpEvent":{"url":"\/documentation\/kakaoadsdk\/sendsignupevent","title":"서비스신청 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendSearchEvent":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","title":"검색 이벤트 전송","role":"article","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/kakaoadsdk\/sendsearchevent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/RequestIDFA":{"url":"\/documentation\/kakaoadsdk\/requestidfa","title":"IDFA 추적 권한 요청","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/RequestIDFA","type":"topic","kind":"article","abstract":[{"type":"text","text":"광고 성과 측정을 정확하게 수행하려면 앱의 추적 권한 요청 시점과 SDK 초기화 시점을 함께 고려해야 합니다."}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendCompleteRegisterEvent":{"role":"article","abstract":[],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","title":"회원가입 이벤트 전송","url":"\/documentation\/kakaoadsdk\/sendcompleteregisterevent","type":"topic","kind":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendPurchaseEvent":{"url":"\/documentation\/kakaoadsdk\/sendpurchaseevent","title":"구매 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendLoginEvent":{"url":"\/documentation\/kakaoadsdk\/sendloginevent","title":"로그인 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent","type":"topic","kind":"article","abstract":[],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendMissionCompleteEvent":{"type":"topic","abstract":[],"role":"article","kind":"article","url":"\/documentation\/kakaoadsdk\/sendmissioncompleteevent","title":"목표달성 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/activate()":{"type":"topic","kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/activate()","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()","role":"symbol","title":"activate()","abstract":[{"type":"text","text":"이벤트 트래커 활성화"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activate"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"text","text":"+ "},{"text":"activate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":[{"title":"연동하기","identifiers":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendCompleteRegisterEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendViewContentEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSearchEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPurchaseEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendParticipationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendSignUpEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendMissionCompleteEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendTutorialEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendPreparationEvent","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendLoginEvent"],"generated":true,"anchor":"연동하기"}],"path":"\/seeAlsoSections","op":"replace"},{"value":"trackId","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/title","op":"replace"},{"value":[{"text":"trackId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/fragments","op":"replace"},{"value":"activate","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"activate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}