{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"()","kind":"text"}]}]},{"mentions":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"kind":"mentions"}],"abstract":[{"type":"text","text":"이벤트 트래커 활성화"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activate"}],"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)activate","roleHeading":"Type Method","title":"activate()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","modules":[{"name":"KakaoAd SDK"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/activate()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/activate()"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()"},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/activate()":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/activate()","navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"activate","kind":"identifier"}],"type":"topic","role":"symbol","title":"activate()","kind":"symbol","abstract":[{"text":"이벤트 트래커 활성화","type":"text"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/activate()","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"activate","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"activate","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","op":"replace","value":"KakaoAdTracker"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"KakaoAdTracker"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle"},{"value":"activate","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1activate()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"activate"}]}]}]}