{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAddToWishListEvent"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"contentId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"tag","content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}]},{"name":"contentId","content":[{"type":"paragraph","inlineContent":[{"text":"콘텐츠\/상품 코드","type":"text"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:contentId:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:contentid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:contentid:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"KakaoAd SDK"}],"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)sendAddToWishListEventWithTag:contentId:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAddToWishListEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"contentId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"roleHeading":"Type Method","role":"symbol","title":"sendAddToWishListEvent(tag:contentId:)","platforms":[],"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToWishListEventWithTag:contentId:"}]},"abstract":[{"text":"관심상품 추가 이벤트","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"이 함수는 더 이상 사용되지 않습니다. 대신 sendAddToWishListEvent(tag:products:)를 사용하세요.","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"sections":[],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToWishListEvent(tag:contentId:)":{"kind":"symbol","title":"sendAddToWishListEvent(tag:contentId:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToWishListEventWithTag:contentId:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sendAddToWishListEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tag"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contentId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"deprecated":true,"role":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:contentid:)","abstract":[{"text":"관심상품 추가 이벤트","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:contentId:)"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"sendAddToWishListEventWithTag:contentId:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sendAddToWishListEventWithTag:contentId:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sendAddToWishListEventWithTag:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tag"},{"text":" ","kind":"text"},{"text":"contentId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contentId"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}],"name":"tag"},{"content":[{"type":"paragraph","inlineContent":[{"text":"콘텐츠\/상품 코드","type":"text"}]}],"name":"contentId"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"type":"text","text":"이 함수는 더 이상 사용되지 않습니다. 대신 sendAddToWishListEvent(tag:products:)를 사용하세요."}]}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:contentId:)\/title","value":"sendAddToWishListEventWithTag:contentId:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:contentId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:contentId:)\/fragments"},{"op":"replace","value":"KakaoAdTracker","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"KakaoAdTracker"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle"}]}]}