{"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendViewContentEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","kind":"typeIdentifier","text":"KakaoAdDetailProduct","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct"},{"kind":"text","text":"])"}]}],"kind":"declarations"},{"parameters":[{"name":"tag","content":[{"inlineContent":[{"text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다.","type":"text"}],"type":"paragraph"}]},{"name":"currency","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"결제 금액 통화 (ISO4217 포맷)"}]}]},{"name":"products","content":[{"inlineContent":[{"text":"KakaoAdDetailProduct 클래스 객체의 Array 타입을 입력 받습니다. 개별 상품 상세 정보의 리스트 입니다.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:currency:products:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:currency:products:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendViewContentEventWithTag:currency:products:"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)sendViewContentEventWithTag:currency:products:","role":"symbol","title":"sendViewContentEvent(tag:currency:products:)","modules":[{"name":"KakaoAd SDK"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendViewContentEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct"},{"kind":"text","text":"])"}]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"title":"KakaoAdDetailProduct","role":"symbol","abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"text":" ","type":"text"},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"KakaoAdDetailProduct"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendViewContentEvent(tag:currency:products:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:currency:products:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendviewcontentevent(tag:currency:products:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendViewContentEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"products","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"KakaoAdDetailProduct","kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"콘텐츠\/상품 조회 이벤트"}],"type":"topic","title":"sendViewContentEvent(tag:currency:products:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendViewContentEvent(tag:currency:products:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"sendViewContentEventWithTag:currency:products:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendViewContentEventWithTag:currency:products:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"sendViewContentEventWithTag:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tag"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"products:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<KakaoAdDetailProduct *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"products","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다.","type":"text"}],"type":"paragraph"}],"name":"tag"},{"content":[{"type":"paragraph","inlineContent":[{"text":"결제 금액 통화 (ISO4217 포맷)","type":"text"}]}],"name":"currency"},{"content":[{"inlineContent":[{"text":"KakaoAdDetailProduct 클래스 객체의 Array 타입을 입력 받습니다. 개별 상품 상세 정보의 리스트 입니다.","type":"text"}],"type":"paragraph"}],"name":"products"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"KakaoAdTracker","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title"},{"value":[{"kind":"identifier","text":"KakaoAdTracker"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments"},{"value":[{"kind":"identifier","text":"KakaoAdTracker"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle"},{"value":"KakaoAdDetailProduct","op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title"},{"value":[{"kind":"identifier","text":"KakaoAdDetailProduct"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments"},{"value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/title","value":"sendViewContentEventWithTag:currency:products:","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendViewContentEvent(tag:currency:products:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendViewContentEventWithTag:currency:products:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}