{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAddToCartEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"contentId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"tag","content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}]},{"name":"contentId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"콘텐츠\/상품 코드"}]}]}]},{"mentions":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent"],"kind":"mentions"}],"metadata":{"title":"sendAddToCartEvent(tag:contentId:)","symbolKind":"method","navigatorTitle":[{"kind":"text","text":"+ "},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAddToCartEvent","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contentId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"role":"symbol","platforms":[],"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)sendAddToCartEventWithTag:contentId:","modules":[{"name":"KakaoAd SDK"}]},"variants":[{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:contentid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:contentid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"이 함수는 더 이상 사용되지 않습니다. 대신 sendAddToCartEvent(tag:products:)를 사용하세요."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"장바구니 추가 이벤트","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToCartEvent(tag:contentId:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtocartevent(tag:contentid:)","title":"sendAddToCartEvent(tag:contentId:)","navigatorTitle":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"sendAddToCartEventWithTag:contentId:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToCartEvent(tag:contentId:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendAddToCartEvent"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"contentId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","kind":"symbol","abstract":[{"text":"장바구니 추가 이벤트","type":"text"}],"role":"symbol","deprecated":true},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","abstract":[{"type":"text","text":"이벤트 수집을 위한 기본 클래스"},{"type":"text","text":" "},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다."}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KakaoAdTracker"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","title":"KakaoAdTracker"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToCartEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtocartevent","title":"장바구니 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToCartEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[]},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"sendAddToCartEventWithTag:contentId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"sendAddToCartEventWithTag:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tag"},{"kind":"text","text":" "},{"text":"contentId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"contentId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다.","type":"text"}],"type":"paragraph"}],"name":"tag"},{"content":[{"inlineContent":[{"text":"콘텐츠\/상품 코드","type":"text"}],"type":"paragraph"}],"name":"contentId"}],"kind":"parameters"},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"type":"text","text":"이 함수는 더 이상 사용되지 않습니다. 대신 sendAddToCartEvent(tag:products:)를 사용하세요."}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/title","value":"sendAddToCartEventWithTag:contentId:","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToCartEvent(tag:contentId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToCartEventWithTag:contentId:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","value":"KakaoAdTracker","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"}]}]}