{"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)sendAddToWishListEventWithTag:currency:products:","symbolKind":"method","modules":[{"name":"KakaoAd SDK"}],"title":"sendAddToWishListEvent(tag:currency:products:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAddToWishListEvent","kind":"identifier"},{"kind":"text","text":"("},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"products"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:currency:products:","kind":"identifier"}],"roleHeading":"Type Method"},"variants":[{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:currency:products:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:currency:products:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:currency:products:)"},"abstract":[{"type":"text","text":"관심상품 추가 이벤트"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendAddToWishListEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"currency","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"products","kind":"externalParam"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"tag","content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"결제 금액 통화 (ISO4217 포맷)","type":"text"}],"type":"paragraph"}],"name":"currency"},{"name":"products","content":[{"type":"paragraph","inlineContent":[{"text":"KakaoAdDetailProduct 클래스 객체의 Array 타입을 입력 받습니다. 개별 상품 상세 정보의 리스트 입니다.","type":"text"}]}]}]},{"kind":"mentions","mentions":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent"]}],"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendAddToWishListEvent(tag:currency:products:)":{"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendaddtowishlistevent(tag:currency:products:)","title":"sendAddToWishListEvent(tag:currency:products:)","navigatorTitle":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"sendAddToWishListEventWithTag:currency:products:"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendAddToWishListEvent(tag:currency:products:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAddToWishListEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currency"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"products"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@KakaoAdSDK@objc(cs)KakaoAdDetailProduct","text":"KakaoAdDetailProduct"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"관심상품 추가 이벤트"}],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","kind":"symbol","role":"collection","abstract":[],"type":"topic","title":"KakaoAd SDK","url":"\/documentation\/kakaoadsdk"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdDetailProduct":{"abstract":[{"text":"구매 이벤트 전송시에 Products 파라메터의 Array 에 들어가는 상세 타입","type":"text"},{"type":"text","text":" "},{"text":"상품명, 수량, 가격 정보를 가지고 있습니다.","type":"text"}],"title":"KakaoAdDetailProduct","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdDetailProduct","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoaddetailproduct","type":"topic","kind":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdDetailProduct","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/SendAddToWishlistEvent":{"url":"\/documentation\/kakaoadsdk\/sendaddtowishlistevent","title":"관심상품 추가 이벤트 전송","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/SendAddToWishlistEvent","type":"topic","kind":"article","abstract":[{"text":"0.8.0부터 이벤트 전송 방식이 확장되었습니다.","type":"text"}],"role":"article"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"kind":"symbol","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","abstract":[{"type":"text","text":"이벤트 수집을 위한 기본 클래스"},{"type":"text","text":" "},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다."}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"KakaoAdTracker"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","title":"KakaoAdTracker"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"sendAddToWishListEventWithTag:currency:products:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:currency:products:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sendAddToWishListEventWithTag:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tag","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"currency:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"currency","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"products:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<KakaoAdDetailProduct *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"products","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}],"name":"tag"},{"content":[{"inlineContent":[{"type":"text","text":"결제 금액 통화 (ISO4217 포맷)"}],"type":"paragraph"}],"name":"currency"},{"content":[{"inlineContent":[{"type":"text","text":"KakaoAdDetailProduct 클래스 객체의 Array 타입을 입력 받습니다. 개별 상품 상세 정보의 리스트 입니다."}],"type":"paragraph"}],"name":"products"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"sendAddToWishListEventWithTag:currency:products:","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:currency:products:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"sendAddToWishListEventWithTag:currency:products:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendAddToWishListEvent(tag:currency:products:)\/fragments"},{"op":"replace","value":"KakaoAdDetailProduct","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/title"},{"op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/fragments"},{"op":"replace","value":[{"text":"KakaoAdDetailProduct","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdDetailProduct\/navigatorTitle"},{"op":"replace","value":"KakaoAdTracker","path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title"},{"op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments"},{"op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}