{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS","iPadOS","Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPreparationEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}]}],"name":"tag"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"사전준비 이벤트"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendPreparationEventWithTag:","kind":"identifier"}],"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cm)sendPreparationEventWithTag:","roleHeading":"Type Method","title":"sendPreparationEvent(tag:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendPreparationEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"role":"symbol","modules":[{"name":"KakaoAd SDK"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpreparationevent(tag:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpreparationevent(tag:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPreparationEvent(tag:)","interfaceLanguage":"swift"},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/sendPreparationEvent(tag:)":{"navigatorTitle":[{"text":"+ ","kind":"text"},{"text":"sendPreparationEventWithTag:","kind":"identifier"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/sendpreparationevent(tag:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendPreparationEvent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"사전준비 이벤트"}],"type":"topic","title":"sendPreparationEvent(tag:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/sendPreparationEvent(tag:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sendPreparationEventWithTag:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"sendPreparationEventWithTag:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sendPreparationEventWithTag:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tag","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"tag","content":[{"inlineContent":[{"type":"text","text":"Tag 의 경우, 한 광고계정 내에서 같은 이벤트코드 내에서도 특별한 분류가 필요할 때 추가합니다."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","value":"KakaoAdTracker","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","value":[{"text":"KakaoAdTracker","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPreparationEvent(tag:)\/title","value":"sendPreparationEventWithTag:","op":"replace"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1sendPreparationEvent(tag:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"sendPreparationEventWithTag:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}