{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"trackId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["swift"]}]},{"mentions":["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker"],"kind":"mentions"}],"abstract":[{"text":"광고계정별로 고유한 식별값.","type":"text"},{"text":" ","type":"text"},{"text":"trackId 를 설정하지 않을 경우 이벤트 수집은 이루어지지 않습니다.","type":"text"}],"sections":[],"metadata":{"externalID":"c:@M@KakaoAdSDK@objc(cs)KakaoAdTracker(cpy)trackId","modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"trackId"}],"role":"symbol","title":"trackId"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/trackid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/kakaoadtracker\/trackid"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker"]]},"references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker/trackId":{"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker\/trackId","navigatorTitle":[{"kind":"identifier","text":"trackId"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/kakaoadsdk\/kakaoadtracker\/trackid","title":"trackId","abstract":[{"type":"text","text":"광고계정별로 고유한 식별값."},{"type":"text","text":" "},{"type":"text","text":"trackId 를 설정하지 않을 경우 이벤트 수집은 이루어지지 않습니다."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"title":"KakaoAd SDK","role":"collection","kind":"symbol","abstract":[],"url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","type":"topic"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/KakaoAdTracker":{"title":"KakaoAdTracker","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KakaoAdTracker","kind":"identifier"}],"navigatorTitle":[{"text":"KakaoAdTracker","kind":"identifier"}],"type":"topic","url":"\/documentation\/kakaoadsdk\/kakaoadtracker","role":"symbol","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/KakaoAdTracker","kind":"symbol","abstract":[{"text":"이벤트 수집을 위한 기본 클래스","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 회원가입, 장바구니 보기, 검색, 구매, 앱내 구매에 대한 이벤트를 이벤트 수집서버로 전송할 수 있습니다.","type":"text"},{"text":" ","type":"text"},{"text":"설치, 실행, 앱내 구매에 대한 이벤트는 이벤트 발생시 자동으로 이벤트 서버로 이벤트가 전송 됩니다.","type":"text"}]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/StartEventTracker":{"kind":"article","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/StartEventTracker","role":"article","abstract":[{"type":"codeVoice","code":"KakaoAdTracker.trackId"},{"text":"는 필수 입력 값입니다.","type":"text"}],"title":"Track ID 설정 및 이벤트 트래커 활성화","type":"topic","url":"\/documentation\/kakaoadsdk\/starteventtracker"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"trackId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"trackId","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS","iPadOS","Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"trackId"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/title","op":"replace","value":"trackId"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker~1trackId\/fragments","op":"replace","value":[{"text":"trackId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/title","op":"replace","value":"KakaoAdTracker"},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/fragments","op":"replace","value":[{"kind":"identifier","text":"KakaoAdTracker"}]},{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1KakaoAdTracker\/navigatorTitle","op":"replace","value":[{"text":"KakaoAdTracker","kind":"identifier"}]}]}]}