{"identifier":{"url":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/init","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"KakaoAd SDK"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@KakaoAdSDK@objc(cs)Logger(im)init","title":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/kakaoadsdk\/logger\/init"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger/init":{"url":"\/documentation\/kakaoadsdk\/logger\/init","title":"init","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol"},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK":{"type":"topic","kind":"symbol","url":"\/documentation\/kakaoadsdk","identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK","role":"collection","title":"KakaoAd SDK","abstract":[]},"doc://com.kakao.biz.KakaoAdSDK/documentation/KakaoAdSDK/Logger":{"url":"\/documentation\/kakaoadsdk\/logger","title":"Logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/com.kakao.biz.KakaoAdSDK\/documentation\/KakaoAdSDK\/Logger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/title","op":"replace","value":"Logger"},{"value":[{"text":"Logger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/fragments","op":"replace"},{"value":[{"text":"Logger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.kakao.biz.KakaoAdSDK~1documentation~1KakaoAdSDK~1Logger\/navigatorTitle","op":"replace"}]}]}